// Code generated by ogen, DO NOT EDIT.

package tonapi

// setDefaults set default value of fields.
func (s *DomainBid) setDefaults() {
	{
		val := bool(false)
		s.Success = val
	}
}

// setDefaults set default value of fields.
func (s *ServiceStatus) setDefaults() {
	{
		val := bool(true)
		s.RestOnline = val
	}
}
